//! Methods for interacting with the LLZK IR.
//! Currently, until the `verif` dialect is implemented, these methods are limited
//! to LLZK IR loading and metadata extraction.
//! In future iterations, we will add functionality to emit `verif` dialect IR,
//! either combined with the LLZK IR or in a separate file.

use crate::diagnostic::CompileError;
use llzk::context::LlzkContext;
use llzk::dialect::{
    array::ArrayType,
    function::{FuncDefOpLike, is_func_def},
    poly::{is_expr_op, is_param_op},
    r#struct::{MemberDefOpLike, StructDefOpLike, StructType, is_struct_def, is_struct_member},
};
use llzk::operation::WalkOperationMutLike;
use llzk::prelude::{FuncDefOpRefMut, MemberDefOpRefMut, PodType, StructDefOpRef};
use melior::{
    dialect::DialectRegistry,
    ir::{
        Module, OperationRef, Type,
        attribute::StringAttribute,
        operation::{OperationLike, WalkOrder, WalkResult},
    },
    utility::register_all_dialects,
};
use mlir_sys::mlirOperationGetParentOperation;
use std::collections::{HashMap, HashSet};

/// Kind of loop operation discovered in LLZK IR.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LoopKind {
    For,
    While,
}

/// Function context for loop names.
///
/// Different functions and structs can reuse the same loop labels, but loop
/// labels cannot be repeated in struct compute/constrain functions.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum LoopScope {
    Struct(String),
    Function(String),
}

/// Metadata needed to verify a spec invariant against an LLZK loop.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoopMetadata {
    pub kind: LoopKind,
    /// Number of loop variables to bind.
    pub binding_count: usize,
    pub scope: LoopScope,
    /// Whether this loop was explicitly labeled in the IR or if the name was
    /// autogenerated.
    pub explicit_label: bool,
}

/// Symbol metadata collected from a parsed LLZK IR module.
#[derive(Debug, Clone)]
pub struct IrMetadata {
    /// Symbol names explicitly defined in the IR.
    pub defined_symbols: HashSet<String>,
    /// All nested member paths discovered from `struct.type` and `pod.type`
    /// members, regardless of public visibility.
    pub all_member_paths: HashSet<String>,
    /// Member paths that specs are allowed to access.
    pub accessible_member_paths: HashSet<String>,
    /// Explicit `loop_label` loops and generated `loopN` loops,
    /// scoped to their containing struct or free function.
    pub labeled_loops: HashMap<(LoopScope, String), LoopMetadata>,
}

/// Parses an LLZK IR module and extracts the metadata needed for symbol verification.
pub fn load_ir(source_name: &str, source: &str) -> Result<IrMetadata, CompileError> {
    let context = LlzkContext::new_no_log();
    let registry = DialectRegistry::new();
    register_all_dialects(&registry);
    context.append_dialect_registry(&registry);
    context.load_all_available_dialects();
    let mut module = Module::parse(&context, source)
        .ok_or_else(|| CompileError::Ir(format!("{source_name}: failed to parse LLZK IR")))?;

    extract_metadata(source_name, &mut module)
}

/// Walks the parsed IR and collects the names needed by semantic verification.
fn extract_metadata(
    source_name: &str,
    module: &mut Module<'_>,
) -> Result<IrMetadata, CompileError> {
    let mut metadata = IrMetadata {
        defined_symbols: HashSet::new(),
        all_member_paths: HashSet::new(),
        accessible_member_paths: HashSet::new(),
        labeled_loops: HashMap::new(),
    };
    let mut duplicate_loop_name = None;
    let mut loop_indices = HashMap::<LoopScope, usize>::new();

    module
        .as_operation_mut()
        .walk_mut(WalkOrder::PreOrder, |operation| {
            // Collect all symbols from relevant symbol defining ops.
            // TODO: Once we add `function.arg_name` attributes, we will collect
            // those here as well.
            if defines_symbol(&operation)
                && let Some(symbol_name) = string_attribute(&operation, "sym_name")
            {
                metadata
                    .defined_symbols
                    .insert(spec_visible_symbol_name(&operation, &symbol_name));
            }

            if let Some(member_op) = MemberDefOpRefMut::from_option_raw(operation.to_raw()) {
                let member_name = member_op.member_name().to_string();
                collect_member_paths(
                    &member_op,
                    &member_name,
                    member_op.member_type(),
                    true,
                    &mut metadata,
                );
            }

            // Collect all the loop scopes
            if let Some((scope, kind, binding_count)) = loop_metadata(&operation) {
                if let Some(loop_name) = string_attribute(&operation, "loop_label") {
                    if metadata
                        .labeled_loops
                        .insert(
                            (scope.clone(), loop_name.clone()),
                            LoopMetadata {
                                kind,
                                binding_count,
                                scope,
                                explicit_label: true,
                            },
                        )
                        .is_some()
                    {
                        duplicate_loop_name = Some(loop_name);
                        return WalkResult::Interrupt;
                    }
                } else {
                    let index = loop_indices.entry(scope.clone()).or_default();
                    let loop_name = format!("loop{index}");
                    *index += 1;
                    metadata.labeled_loops.insert(
                        (scope.clone(), loop_name),
                        LoopMetadata {
                            kind,
                            binding_count,
                            scope,
                            explicit_label: false,
                        },
                    );
                }
            }

            WalkResult::Advance
        });

    if let Some(loop_name) = duplicate_loop_name {
        Err(CompileError::Ir(format!(
            "{source_name}: duplicate loop name `{loop_name}`"
        )))
    } else {
        Ok(metadata)
    }
}

/// Finds the owner scope for a loop. Struct methods use the nearest `struct.def`,
/// standalone functions use the nearest `function.def`, and loops inside `poly.expr`
/// are intentionally ignored.
fn containing_loop_scope<'c: 'a, 'a>(operation: &impl OperationLike<'c, 'a>) -> Option<LoopScope> {
    // TODO: Once we update melior, we shouldn't need these unsafe handlers.
    fn get_parent<'c: 'a, 'a>(op: &impl OperationLike<'c, 'a>) -> Option<OperationRef<'c, 'a>> {
        let raw_parent = unsafe { mlirOperationGetParentOperation(op.to_raw()) };
        (!raw_parent.ptr.is_null()).then_some(unsafe { OperationRef::from_raw(raw_parent) })
    }

    let mut opt_parent = get_parent(operation);
    let mut function_scope = None;
    while let Some(parent) = opt_parent {
        if is_expr_op(&parent) {
            return None;
        }
        if is_struct_def(&parent)
            && let Some(struct_name) = string_attribute(&parent, "sym_name")
        {
            return Some(LoopScope::Struct(spec_visible_symbol_name(
                &parent,
                &struct_name,
            )));
        }
        if is_func_def(&parent)
            && let Some(function_name) = string_attribute(&parent, "sym_name")
        {
            function_scope = Some(LoopScope::Function(spec_visible_symbol_name(
                &parent,
                &function_name,
            )));
        }
        opt_parent = get_parent(&parent);
    }
    function_scope
}

/// Computes a fully qualified symbol name by prepending named enclosing
/// `builtin.module` operations.
fn qualified_symbol_name<'c: 'a, 'a>(
    operation: &impl OperationLike<'c, 'a>,
    symbol_name: &str,
) -> String {
    let mut components = module_ancestor_names(operation);
    components.push(symbol_name.to_string());
    components.join("::")
}

/// Returns the enclosing named builtin modules from outermost to innermost.
fn module_ancestor_names<'c: 'a, 'a>(operation: &impl OperationLike<'c, 'a>) -> Vec<String> {
    // TODO: Once we update melior, we shouldn't need these unsafe handlers.
    fn get_parent<'c: 'a, 'a>(op: &impl OperationLike<'c, 'a>) -> Option<OperationRef<'c, 'a>> {
        let raw_parent = unsafe { mlirOperationGetParentOperation(op.to_raw()) };
        (!raw_parent.ptr.is_null()).then_some(unsafe { OperationRef::from_raw(raw_parent) })
    }

    let mut names = Vec::new();
    let mut opt_parent = get_parent(operation);
    while let Some(parent) = opt_parent {
        if parent.name().as_string_ref().as_str().ok() == Some("builtin.module")
            && let Some(module_name) = string_attribute(&parent, "sym_name")
        {
            names.push(module_name);
        }
        opt_parent = get_parent(&parent);
    }
    names.reverse();
    names
}

fn collect_member_paths<'c: 'a, 'a>(
    root: &impl OperationLike<'c, 'a>,
    prefix: &str,
    member_type: Type<'c>,
    parent_accessible: bool,
    metadata: &mut IrMetadata,
) {
    if let Ok(struct_type) = StructType::try_from(member_type) {
        collect_struct_member_paths(root, prefix, struct_type, parent_accessible, metadata);
    } else if let Ok(pod_type) = PodType::try_from(member_type) {
        collect_pod_member_paths(root, prefix, pod_type, parent_accessible, metadata);
    } else if let Ok(array_type) = ArrayType::try_from(member_type) {
        collect_array_member_paths(root, prefix, array_type, parent_accessible, metadata);
    }
}

fn collect_struct_member_paths<'c: 'a, 'a>(
    root: &impl OperationLike<'c, 'a>,
    prefix: &str,
    struct_type: StructType<'c>,
    parent_accessible: bool,
    metadata: &mut IrMetadata,
) {
    let Ok(lookup) = struct_type.get_definition(root) else {
        return;
    };
    let Some(operation) = lookup.get_operation() else {
        return;
    };
    let Ok(struct_def) = StructDefOpRef::try_from(operation) else {
        return;
    };

    for member in struct_def.get_member_defs() {
        let path = format!("{prefix}.{}", member.member_name());
        metadata.all_member_paths.insert(path.clone());
        let accessible = parent_accessible && member.has_public_attr();
        if accessible {
            metadata.accessible_member_paths.insert(path.clone());
        }
        collect_member_paths(&member, &path, member.member_type(), accessible, metadata);
    }
}

fn collect_pod_member_paths<'c: 'a, 'a>(
    root: &impl OperationLike<'c, 'a>,
    prefix: &str,
    pod_type: PodType<'c>,
    parent_accessible: bool,
    metadata: &mut IrMetadata,
) {
    for record in pod_type.get_records() {
        let record_name = record
            .name()
            .as_string_ref()
            .as_str()
            .unwrap_or("")
            .trim_start_matches('@')
            .to_string();
        let path = format!("{prefix}.{record_name}");
        metadata.all_member_paths.insert(path.clone());
        if parent_accessible {
            metadata.accessible_member_paths.insert(path.clone());
        }
        collect_member_paths(root, &path, record.r#type(), parent_accessible, metadata);
    }
}

fn collect_array_member_paths<'c: 'a, 'a>(
    root: &impl OperationLike<'c, 'a>,
    prefix: &str,
    array_type: ArrayType<'c>,
    parent_accessible: bool,
    metadata: &mut IrMetadata,
) {
    collect_member_paths(
        root,
        prefix,
        array_type.element_type(),
        parent_accessible,
        metadata,
    );
}

/// Returns the spec-visible name for an IR symbol.
///
/// Contract targets should use fully qualified names when nested in named
/// modules. Locals that are referenced inside contracts, such as struct members
/// and `poly.param`s, remain unqualified.
fn spec_visible_symbol_name<'c: 'a, 'a>(
    operation: &impl OperationLike<'c, 'a>,
    symbol_name: &str,
) -> String {
    if is_struct_def(operation) {
        // TODO: We use this path because of a current todo! in llzk-rs in
        // get_fully_qualified_name().
        qualified_symbol_name(operation, symbol_name)
    } else if let Some(func_op) = FuncDefOpRefMut::from_option_raw(operation.to_raw()) {
        func_op.fully_qualified_name().to_string()
    } else {
        symbol_name.to_string()
    }
}

/// Returns the string value for a string-valued operation attribute when present.
fn string_attribute<'c: 'a, 'a>(
    operation: &impl OperationLike<'c, 'a>,
    name: &str,
) -> Option<String> {
    operation
        .attribute(name)
        .ok()
        .and_then(|attribute| StringAttribute::try_from(attribute).ok())
        .map(|attribute| attribute.value().to_string())
}

/// Returns whether an operation contributes a new named symbol to the module.
fn defines_symbol<'c: 'a, 'a>(operation: &impl OperationLike<'c, 'a>) -> bool {
    is_struct_def(operation)
        || is_struct_member(operation)
        || is_func_def(operation)
        || is_param_op(operation)
        || is_expr_op(operation)
}

/// Returns loop scope, kind, and expected invariant binding count for supported loop ops.
fn loop_metadata<'c: 'a, 'a>(
    operation: &impl OperationLike<'c, 'a>,
) -> Option<(LoopScope, LoopKind, usize)> {
    let scope = containing_loop_scope(operation)?;
    let identifier = operation.name();
    let name = identifier.as_string_ref().as_str().ok()?;
    match name {
        // scf.for operands are lower bound, upper bound, step, and iter args.
        // The invariant also binds the induction variable, so add one.
        "scf.for" => Some((scope, LoopKind::For, operation.operand_count() + 1)),
        // scf.while operands are the loop-carried values that become block args.
        "scf.while" => Some((scope, LoopKind::While, operation.operand_count())),
        _ => None,
    }
}
