//! Parsing for the `llzk-spec` language.
//!
//! `pest` is responsible for recognizing the concrete syntax described in
//! [`llzk_spec.pest`](./grammar/llzk_spec.pest). The remainder of this module
//! focuses on lowering the generated parse tree into the llzk-spec AST.

use crate::ast::*;
use crate::diagnostic::Diagnostic;
use pest::Parser;
use pest::Span as PestSpan;
use pest::iterators::{Pair, Pairs};
use pest::pratt_parser::{Assoc, Op, PrattParser};
use pest_derive::Parser;

/// Parser generated from the `llzk-spec` PEG grammar.
///
/// NOTE: The [`Rule`] enum that appears in this file is autogenerated from here
/// as well, and the enum entries are named after the rules in this file.
#[derive(Parser)]
#[grammar = "grammar/llzk_spec.pest"]
struct LlzkSpecParser;

/// Parses a complete `llzk-spec` source file into an AST document.
pub fn parse_document(source_name: &str, source: &str) -> Result<Document, Diagnostic> {
    let pairs = LlzkSpecParser::parse(Rule::file, source).map_err(|error| {
        let (line, column) = match error.line_col {
            pest::error::LineColLocation::Pos((line, column)) => (line, column),
            pest::error::LineColLocation::Span((line, column), _) => (line, column),
        };
        Diagnostic::new(
            source_name,
            format!("syntax error: {error}"),
            Some(Span {
                start: 0,
                end: 0,
                line,
                column,
            }),
        )
    })?;

    Lowerer::new(source_name).document(pairs)
}

/// Lowers the `pest` parse tree into the AST.
struct Lowerer<'a> {
    /// User-facing source name used in diagnostics, usually the spec file path.
    source_name: &'a str,
    /// Pratt parser used to lower precedence-sensitive expression subtrees.
    pratt: PrattParser<Rule>,
}

impl<'a> Lowerer<'a> {
    /// Creates a new lowering context for a single source file.
    fn new(source_name: &'a str) -> Self {
        let pratt = PrattParser::new()
            // Operators are listed from lowest to highest precedence. `Assoc`
            // selects how chains at the same precedence group nest.
            .op(Op::infix(Rule::or_op, Assoc::Left))
            .op(Op::infix(Rule::and_op, Assoc::Left))
            .op(Op::infix(Rule::eq_op, Assoc::Left))
            .op(Op::infix(Rule::rel_op, Assoc::Left))
            .op(Op::infix(Rule::add_op, Assoc::Left))
            .op(Op::infix(Rule::mul_op, Assoc::Left))
            .op(Op::infix(Rule::pow_op, Assoc::Right))
            .op(Op::prefix(Rule::unary_op));

        Self { source_name, pratt }
    }

    /// Lowers the top-level file pair into a document.
    fn document(&self, mut pairs: Pairs<'a, Rule>) -> Result<Document, Diagnostic> {
        let file = pairs.next().expect("file pair");
        let items = file
            .into_inner()
            .filter(|pair| pair.as_rule() != Rule::EOI)
            .map(|pair| self.item(pair))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Document { items })
    }

    /// Lowers a top-level item.
    fn item(&self, pair: Pair<'a, Rule>) -> Result<Item, Diagnostic> {
        match pair.as_rule() {
            Rule::item => self.item(pair.into_inner().next().expect("nested item")),
            Rule::contract_decl => Ok(Item::Contract(self.contract_decl(pair)?)),
            Rule::predicate_decl => Ok(Item::Predicate(self.predicate_decl(pair)?)),
            _ => self.unexpected(pair, "item"),
        }
    }

    /// Lowers a contract declaration.
    fn contract_decl(&self, pair: Pair<'a, Rule>) -> Result<ContractDecl, Diagnostic> {
        let span = self.span(pair.as_span());
        let mut inner = pair.into_inner();
        let target = self.identifier(inner.next().expect("contract target"))?;
        let body = self.block(inner.next().expect("contract body"))?;
        Ok(ContractDecl { target, body, span })
    }

    /// Lowers a predicate declaration.
    fn predicate_decl(&self, pair: Pair<'a, Rule>) -> Result<PredicateDecl, Diagnostic> {
        let span = self.span(pair.as_span());
        let mut inner = pair.into_inner();
        let name = self.identifier(inner.next().expect("predicate name"))?;
        let params = self.param_list(inner.next().expect("predicate params"))?;
        let body_pair = inner.next().expect("predicate body");
        let body = match body_pair.as_rule() {
            Rule::block_predicate_body => {
                self.block(body_pair.into_inner().next().expect("predicate block"))?
            }
            _ => Block {
                statements: vec![Statement::Return {
                    expression: self.expression(body_pair)?,
                    span,
                }],
                span,
            },
        };

        Ok(PredicateDecl {
            name,
            params,
            body,
            span,
        })
    }

    /// Lowers a parameter list.
    fn param_list(&self, pair: Pair<'a, Rule>) -> Result<Vec<Identifier>, Diagnostic> {
        pair.into_inner()
            .map(|pair| self.identifier(pair))
            .collect()
    }

    /// Lowers a statement block.
    fn block(&self, pair: Pair<'a, Rule>) -> Result<Block, Diagnostic> {
        let span = self.span(pair.as_span());
        let statements = pair
            .into_inner()
            .map(|pair| self.statement(pair))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Block { statements, span })
    }

    /// Lowers a statement.
    fn statement(&self, pair: Pair<'a, Rule>) -> Result<Statement, Diagnostic> {
        match pair.as_rule() {
            Rule::statement => self.statement(pair.into_inner().next().expect("statement")),
            Rule::scoped_stmt => self.scoped_stmt(pair),
            Rule::require_stmt => {
                let span = self.span(pair.as_span());
                let expression =
                    self.expression(pair.into_inner().next().expect("require expr"))?;
                Ok(Statement::Require { expression, span })
            }
            Rule::ensure_stmt => {
                let span = self.span(pair.as_span());
                let expression = self.expression(pair.into_inner().next().expect("ensure expr"))?;
                Ok(Statement::Ensure { expression, span })
            }
            Rule::let_stmt => {
                let span = self.span(pair.as_span());
                let mut inner = pair.into_inner();
                let name = self.identifier(inner.next().expect("let name"))?;
                let value = self.expression(inner.next().expect("let value"))?;
                Ok(Statement::Let { name, value, span })
            }
            Rule::unused_stmt => {
                let span = self.span(pair.as_span());
                let name = self.identifier(pair.into_inner().next().expect("unused name"))?;
                Ok(Statement::Unused { name, span })
            }
            Rule::return_stmt => {
                let span = self.span(pair.as_span());
                let expression = self.expression(pair.into_inner().next().expect("return expr"))?;
                Ok(Statement::Return { expression, span })
            }
            Rule::increases_stmt => {
                let span = self.span(pair.as_span());
                let expression =
                    self.expression(pair.into_inner().next().expect("increases expr"))?;
                Ok(Statement::Increases { expression, span })
            }
            Rule::decreases_stmt => {
                let span = self.span(pair.as_span());
                let expression =
                    self.expression(pair.into_inner().next().expect("decreases expr"))?;
                Ok(Statement::Decreases { expression, span })
            }
            Rule::step_stmt => {
                let span = self.span(pair.as_span());
                let expression = self.expression(pair.into_inner().next().expect("step expr"))?;
                Ok(Statement::Step { expression, span })
            }
            Rule::invariant_decl => Ok(Statement::Invariant(self.invariant_decl(pair)?)),
            Rule::predicate_decl => Ok(Statement::Predicate(self.predicate_decl(pair)?)),
            Rule::semi => Err(Diagnostic::new(
                self.source_name,
                "empty statements are not allowed",
                Some(self.span(pair.as_span())),
            )),
            Rule::block => Ok(Statement::Block(self.block(pair)?)),
            _ => self.unexpected(pair, "statement"),
        }
    }

    /// Lowers a scoped statement such as `compute ensure ...`.
    fn scoped_stmt(&self, pair: Pair<'a, Rule>) -> Result<Statement, Diagnostic> {
        let span = self.span(pair.as_span());
        let mut inner = pair.into_inner();
        let scope = match inner.next().expect("scope prefix").as_str() {
            "compute" | "witness" => Scope::Compute,
            "constrain" => Scope::Constrain,
            other => {
                return Err(Diagnostic::new(
                    self.source_name,
                    format!("unknown scope prefix `{other}`"),
                    Some(span),
                ));
            }
        };
        let statement = Box::new(self.statement(inner.next().expect("scoped statement"))?);
        Ok(Statement::Scoped {
            scope,
            statement,
            span,
        })
    }

    /// Lowers an invariant declaration.
    fn invariant_decl(&self, pair: Pair<'a, Rule>) -> Result<InvariantDecl, Diagnostic> {
        let span = self.span(pair.as_span());
        let mut inner = pair.into_inner();
        let loop_name = self.identifier(inner.next().expect("loop name"))?;
        let bindings = self.binding_list(inner.next().expect("invariant bindings"))?;
        let body = self.block(inner.next().expect("invariant body"))?;
        Ok(InvariantDecl {
            loop_name,
            bindings,
            body,
            span,
        })
    }

    /// Lowers a comma-separated invariant binding list.
    fn binding_list(&self, pair: Pair<'a, Rule>) -> Result<Vec<Identifier>, Diagnostic> {
        pair.into_inner()
            .map(|pair| self.identifier(pair))
            .collect()
    }

    /// Lowers an expression by dispatching to the generated `pest` parse tree.
    fn expression(&self, pair: Pair<'a, Rule>) -> Result<Expression, Diagnostic> {
        match pair.as_rule() {
            Rule::expression => self.expression(pair.into_inner().next().expect("expression")),
            Rule::conditional_expr => self.conditional_expression(pair),
            Rule::logical_or_expr
            | Rule::logical_and_expr
            | Rule::equality_expr
            | Rule::relational_expr
            | Rule::additive_expr
            | Rule::multiplicative_expr
            | Rule::power_expr
            | Rule::unary_expr => self.pratt_expression(pair),
            Rule::postfix_expr => self.postfix_expression(pair),
            Rule::primary_expr => self.expression(pair.into_inner().next().expect("primary expr")),
            Rule::quantifier_expr => self.quantifier_expression(pair),
            Rule::len_expr => {
                let span = self.span(pair.as_span());
                let target = self.expression(pair.into_inner().next().expect("len target"))?;
                Ok(Expression::Len {
                    target: Box::new(target),
                    span,
                })
            }
            Rule::old_expr => {
                let span = self.span(pair.as_span());
                let expression = self.expression(pair.into_inner().next().expect("old expr"))?;
                Ok(Expression::Old {
                    expression: Box::new(expression),
                    span,
                })
            }
            Rule::arg_ref => self.arg_ref(pair),
            Rule::nondet_expr => Ok(Expression::Nondet {
                span: self.span(pair.as_span()),
            }),
            Rule::boolean => Ok(Expression::Boolean {
                value: pair.as_str() == "true",
                span: self.span(pair.as_span()),
            }),
            Rule::number => Ok(Expression::Number {
                value: pair.as_str().to_string(),
                span: self.span(pair.as_span()),
            }),
            Rule::symbol | Rule::escaped_symbol => Ok(Expression::Symbol(self.identifier(pair)?)),
            _ => self.unexpected(pair, "expression"),
        }
    }

    /// Lowers `arg[N]`, a reference to an unnamed function argument (i.e., does
    /// not have the `function.arg_name` attribute).
    fn arg_ref(&self, pair: Pair<'a, Rule>) -> Result<Expression, Diagnostic> {
        let span = self.span(pair.as_span());
        let index_pair = pair.into_inner().next().expect("arg index");
        let index = index_pair.as_str().parse::<usize>().map_err(|_| {
            Diagnostic::new(
                self.source_name,
                format!("argument index `{}` is too large", index_pair.as_str()),
                Some(self.span(index_pair.as_span())),
            )
        })?;
        Ok(Expression::Arg { index, span })
    }

    /// Lowers a conditional expression, using `pest` for the condition subtree.
    fn conditional_expression(&self, pair: Pair<'a, Rule>) -> Result<Expression, Diagnostic> {
        let span = self.span(pair.as_span());
        let mut inner = pair.into_inner();
        let condition = self.expression(inner.next().expect("condition"))?;
        if let Some(then_pair) = inner.next() {
            let else_pair = inner.next().expect("else branch");
            Ok(Expression::Conditional {
                condition: Box::new(condition),
                then_branch: Box::new(self.expression(then_pair)?),
                else_branch: Box::new(self.expression(else_pair)?),
                span,
            })
        } else {
            Ok(condition)
        }
    }

    /// Lowers a precedence-sensitive expression using `pest`'s Pratt parser.
    fn pratt_expression(&self, pair: Pair<'a, Rule>) -> Result<Expression, Diagnostic> {
        self.pratt
            .map_primary(|primary| self.expression(primary))
            .map_prefix(|operator, rhs| {
                let rhs = rhs?;
                let rhs_span = rhs.span();
                let op = match operator.as_str() {
                    "!" => UnaryOp::Not,
                    "-" => UnaryOp::Neg,
                    other => {
                        return Err(Diagnostic::new(
                            self.source_name,
                            format!("unknown unary operator `{other}`"),
                            Some(self.span(operator.as_span())),
                        ));
                    }
                };
                Ok(Expression::Unary {
                    op,
                    expr: Box::new(rhs),
                    span: self.join_spans(operator.as_span(), rhs_span),
                })
            })
            .map_infix(|lhs, operator, rhs| {
                let lhs = lhs?;
                let rhs = rhs?;
                let lhs_span = lhs.span();
                let rhs_span = rhs.span();
                Ok(Expression::Binary {
                    op: self.binary_op(operator.as_rule(), operator.as_str())?,
                    left: Box::new(lhs),
                    right: Box::new(rhs),
                    span: self.join_expression_spans(lhs_span, rhs_span),
                })
            })
            .parse(pair.into_inner())
    }

    /// Lowers a postfix expression such as indexing or predicate calls.
    fn postfix_expression(&self, pair: Pair<'a, Rule>) -> Result<Expression, Diagnostic> {
        let mut inner = pair.into_inner();
        let mut expr = self.expression(inner.next().expect("postfix base"))?;
        for suffix in inner {
            match suffix.as_rule() {
                Rule::index_op => {
                    let index = self.expression(suffix.into_inner().next().expect("index expr"))?;
                    let span = self.join_expression_spans(expr.span(), index.span());
                    expr = Expression::Index {
                        target: Box::new(expr),
                        index: Box::new(index),
                        span,
                    };
                }
                Rule::member_op => {
                    let member =
                        self.identifier(suffix.into_inner().next().expect("member name"))?;
                    let span = self.join_expression_spans(expr.span(), member.span);
                    expr = Expression::Member {
                        target: Box::new(expr),
                        member,
                        span,
                    };
                }
                Rule::call_suffix => {
                    let suffix_span = suffix.as_span();
                    let args = suffix
                        .into_inner()
                        .map(|pair| self.expression(pair))
                        .collect::<Result<Vec<_>, _>>()?;
                    let callee = match expr {
                        Expression::Symbol(identifier) => identifier,
                        other => {
                            return Err(Diagnostic::new(
                                self.source_name,
                                "only named predicate calls are supported in phase 1",
                                Some(other.span()),
                            ));
                        }
                    };
                    let span = self.join_start_to_suffix(callee.span, suffix_span);
                    expr = Expression::Call { callee, args, span };
                }
                _ => return self.unexpected(suffix, "postfix suffix"),
            }
        }
        Ok(expr)
    }

    /// Lowers a quantifier expression and its bound domain.
    fn quantifier_expression(&self, pair: Pair<'a, Rule>) -> Result<Expression, Diagnostic> {
        let span = self.span(pair.as_span());
        let mut inner = pair.into_inner();
        let quantifier_kind = match inner.next().expect("quantifier kind").as_str() {
            "forall" => QuantifierKind::Forall,
            "exists" => QuantifierKind::Exists,
            other => {
                return Err(Diagnostic::new(
                    self.source_name,
                    format!("unknown quantifier `{other}`"),
                    Some(span),
                ));
            }
        };
        let binding = self.identifier(inner.next().expect("quantifier binding"))?;
        let domain = self.quantifier_domain(inner.next().expect("quantifier domain"))?;
        let body = self.expression(inner.next().expect("quantifier body"))?;
        Ok(Expression::Quantifier {
            quantifier_kind,
            binding,
            domain,
            body: Box::new(body),
            span,
        })
    }

    /// Lowers a quantifier domain into either a range or general expression.
    fn quantifier_domain(&self, pair: Pair<'a, Rule>) -> Result<QuantifierDomain, Diagnostic> {
        let pair = if pair.as_rule() == Rule::quantifier_domain {
            pair.into_inner().next().expect("quantifier domain body")
        } else {
            pair
        };

        match pair.as_rule() {
            Rule::range_expr => {
                let span = self.span(pair.as_span());
                let mut inner = pair.into_inner();
                let start = self.expression(inner.next().expect("range start"))?;
                let end = self.expression(inner.next().expect("range end"))?;
                Ok(QuantifierDomain::Range {
                    start: Box::new(start),
                    end: Box::new(end),
                    span,
                })
            }
            _ => Ok(QuantifierDomain::Expr(Box::new(self.expression(pair)?))),
        }
    }

    /// Lowers a symbol occurrence into an identifier with source location.
    fn identifier(&self, pair: Pair<'a, Rule>) -> Result<Identifier, Diagnostic> {
        match pair.as_rule() {
            Rule::symbol => Ok(Identifier {
                name: pair.as_str().to_string(),
                span: self.span(pair.as_span()),
            }),
            Rule::escaped_symbol => {
                let span = self.span(pair.as_span());
                let text = pair.as_str();
                let name = &text[1..text.len() - 1];
                if name.is_empty() {
                    Err(Diagnostic::new(
                        self.source_name,
                        "escaped symbol cannot be empty",
                        Some(span),
                    ))
                } else {
                    Ok(Identifier {
                        name: name.to_string(),
                        span,
                    })
                }
            }
            _ => self.unexpected(pair, "identifier"),
        }
    }

    /// Maps a parsed infix operator token onto the semantic AST operator enum.
    fn binary_op(&self, rule: Rule, text: &str) -> Result<BinaryOp, Diagnostic> {
        let op = match (rule, text) {
            (Rule::or_op, "||") => BinaryOp::Or,
            (Rule::and_op, "&&") => BinaryOp::And,
            (Rule::eq_op, "==") => BinaryOp::Eq,
            (Rule::eq_op, "!=") => BinaryOp::Ne,
            (Rule::rel_op, "<") => BinaryOp::Lt,
            (Rule::rel_op, "<=") => BinaryOp::Le,
            (Rule::rel_op, ">") => BinaryOp::Gt,
            (Rule::rel_op, ">=") => BinaryOp::Ge,
            (Rule::add_op, "+") => BinaryOp::Add,
            (Rule::add_op, "-") => BinaryOp::Sub,
            (Rule::mul_op, "*") => BinaryOp::Mul,
            (Rule::mul_op, "/") => BinaryOp::Div,
            (Rule::mul_op, "%") => BinaryOp::Mod,
            (Rule::mul_op, "&") => BinaryOp::BitAnd,
            (Rule::pow_op, "**") => BinaryOp::Pow,
            _ => {
                return Err(Diagnostic::new(
                    self.source_name,
                    format!("unknown operator `{text}`"),
                    None,
                ));
            }
        };
        Ok(op)
    }

    /// Converts a `pest` span into the compiler's source span representation.
    fn span(&self, span: PestSpan<'a>) -> Span {
        let (line, column) = span.start_pos().line_col();
        Span {
            start: span.start(),
            end: span.end(),
            line,
            column,
        }
    }

    /// Creates a span from the start of one parsed token to the end of another AST node.
    fn join_spans(&self, start: PestSpan<'a>, end: Span) -> Span {
        let (line, column) = start.start_pos().line_col();
        Span {
            start: start.start(),
            end: end.end,
            line,
            column,
        }
    }

    /// Creates a span that covers two AST expressions.
    fn join_expression_spans(&self, start: Span, end: Span) -> Span {
        Span {
            start: start.start,
            end: end.end,
            line: start.line,
            column: start.column,
        }
    }

    /// Creates a span from an AST node start to the end of a parsed suffix.
    fn join_start_to_suffix(&self, start: Span, end: PestSpan<'a>) -> Span {
        Span {
            start: start.start,
            end: end.end(),
            line: start.line,
            column: start.column,
        }
    }

    /// Builds a consistent "unexpected rule" diagnostic while lowering.
    fn unexpected<T>(&self, pair: Pair<'a, Rule>, expected: &str) -> Result<T, Diagnostic> {
        Err(Diagnostic::new(
            self.source_name,
            format!("expected {expected}, found {:?}", pair.as_rule()),
            Some(self.span(pair.as_span())),
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{BinaryOp, Expression, Item, QuantifierDomain, Scope, Statement};

    #[test]
    fn parses_contract_and_predicate_forms() {
        let source = r#"
contract for Foo {
  ensure out == 1;
  predicate local(x) = x + 1
}
predicate ok(x) { return x == 0; }
"#;
        let document = parse_document("test.spec", source).expect("parse success");
        assert_eq!(document.items.len(), 2);
        match &document.items[0] {
            Item::Contract(contract) => {
                assert_eq!(contract.target.name, "Foo");
                assert!(matches!(
                    contract.body.statements[1],
                    Statement::Predicate(_)
                ));
            }
            other => panic!("unexpected item: {other:?}"),
        }
    }

    macro_rules! predicate_body_as_expr {
        ($pattern:pat, $pred:expr, $err:expr) => {
            let [
                Statement::Return {
                    expression: $pattern,
                    ..
                },
            ] = &$pred.body.statements[..]
            else {
                panic!($err);
            };
        };
    }

    #[test]
    fn preserves_expression_precedence() {
        let source = "predicate p(x) = x + 2 * 3 ** 4";
        let document = parse_document("test.spec", source).expect("parse success");
        let Item::Predicate(predicate) = &document.items[0] else {
            panic!("expected predicate");
        };
        predicate_body_as_expr!(
            Expression::Binary { op, right, .. },
            predicate,
            "expected additive expression"
        );
        assert_eq!(*op, BinaryOp::Add);
        let Expression::Binary { op, .. } = right.as_ref() else {
            panic!("expected multiplicative expression");
        };
        assert_eq!(*op, BinaryOp::Mul);
    }

    #[test]
    fn parses_quantifier_domain_range() {
        let source = "predicate p(xs) = forall i in 0..len(xs), xs[i] == 0";
        let document = parse_document("test.spec", source).expect("parse success");
        let Item::Predicate(predicate) = &document.items[0] else {
            panic!("expected predicate");
        };
        predicate_body_as_expr!(
            Expression::Quantifier { domain, .. },
            predicate,
            "expected quantifier"
        );
        assert!(matches!(domain, QuantifierDomain::Range { .. }));
    }

    #[test]
    fn lowers_witness_scope_to_compute() {
        let source = "contract for Foo { witness ensure out == 0; }";
        let document = parse_document("test.spec", source).expect("parse success");
        let Item::Contract(contract) = &document.items[0] else {
            panic!("expected contract");
        };
        let Statement::Scoped { scope, .. } = &contract.body.statements[0] else {
            panic!("expected scoped statement");
        };
        assert_eq!(*scope, Scope::Compute);
    }

    #[test]
    fn parses_argument_references() {
        let source = "contract for Foo { ensure len(arg[0]) == arg[0][i]; }";
        let document = parse_document("test.spec", source).expect("parse success");
        let Item::Contract(contract) = &document.items[0] else {
            panic!("expected contract");
        };
        let Statement::Ensure { expression, .. } = &contract.body.statements[0] else {
            panic!("expected ensure statement");
        };
        let Expression::Binary { left, right, .. } = expression else {
            panic!("expected equality expression");
        };
        let Expression::Len { target, .. } = left.as_ref() else {
            panic!("expected len expression");
        };
        assert!(matches!(target.as_ref(), Expression::Arg { index: 0, .. }));

        let Expression::Index { target, .. } = right.as_ref() else {
            panic!("expected indexed arg expression");
        };
        assert!(matches!(target.as_ref(), Expression::Arg { index: 0, .. }));
    }

    #[test]
    fn parses_member_access_and_indexing() {
        let source = "contract for Foo { ensure child.arr_pub[0] == pod.count; }";
        let document = parse_document("test.spec", source).expect("parse success");
        let Item::Contract(contract) = &document.items[0] else {
            panic!("expected contract");
        };
        let Statement::Ensure { expression, .. } = &contract.body.statements[0] else {
            panic!("expected ensure statement");
        };
        let Expression::Binary { left, right, .. } = expression else {
            panic!("expected equality expression");
        };
        let Expression::Index { target, .. } = left.as_ref() else {
            panic!("expected indexed expression");
        };
        let Expression::Member { target, member, .. } = target.as_ref() else {
            panic!("expected member expression");
        };
        assert_eq!(member.name, "arr_pub");
        assert!(matches!(
            target.as_ref(),
            Expression::Symbol(identifier) if identifier.name == "child"
        ));

        let Expression::Member { target, member, .. } = right.as_ref() else {
            panic!("expected member expression");
        };
        assert_eq!(member.name, "count");
        assert!(matches!(
            target.as_ref(),
            Expression::Symbol(identifier) if identifier.name == "pod"
        ));
    }

    #[test]
    fn parses_multi_binding_invariant_steps_and_variant_statements() {
        let source = r#"
contract for Foo {
  invariant for loop0(lb, i, ub, step) {
    decreases ub - i;
    increases i;
    step i == old(i) + step;
  }
}
"#;
        let document = parse_document("test.spec", source).expect("parse success");
        let Item::Contract(contract) = &document.items[0] else {
            panic!("expected contract");
        };
        let Statement::Invariant(invariant) = &contract.body.statements[0] else {
            panic!("expected invariant");
        };
        assert_eq!(invariant.loop_name.name, "loop0");
        assert_eq!(invariant.bindings.len(), 4);
        assert!(matches!(
            invariant.body.statements[0],
            Statement::Decreases { .. }
        ));
        assert!(matches!(
            invariant.body.statements[1],
            Statement::Increases { .. }
        ));
        let Statement::Step { expression, .. } = &invariant.body.statements[2] else {
            panic!("expected step");
        };
        let Expression::Binary { left, right, .. } = expression else {
            panic!("expected step equality");
        };
        assert!(matches!(
            left.as_ref(),
            Expression::Symbol(identifier) if identifier.name == "i"
        ));
        let Expression::Binary { left, .. } = right.as_ref() else {
            panic!("expected step transition");
        };
        assert!(matches!(left.as_ref(), Expression::Old { .. }));
    }

    #[test]
    fn rejects_empty_invariant_binding_lists() {
        let diagnostic =
            parse_document("test.spec", "contract for Foo { invariant for loop0() {} }")
                .expect_err("parse failure");
        assert!(diagnostic.message.contains("syntax error"));
    }

    #[test]
    fn parses_escaped_reserved_symbols() {
        let source = "contract for `contract` { ensure `return` == `return`; }";
        let document = parse_document("test.spec", source).expect("parse success");
        let Item::Contract(contract) = &document.items[0] else {
            panic!("expected contract");
        };
        assert_eq!(contract.target.name, "contract");

        let Statement::Ensure { expression, .. } = &contract.body.statements[0] else {
            panic!("expected ensure statement");
        };
        let Expression::Binary { left, right, .. } = expression else {
            panic!("expected equality expression");
        };
        assert!(matches!(
            left.as_ref(),
            Expression::Symbol(identifier) if identifier.name == "return"
        ));
        assert!(matches!(
            right.as_ref(),
            Expression::Symbol(identifier) if identifier.name == "return"
        ));
    }

    #[test]
    fn parses_fully_qualified_identifiers() {
        let source = "contract for Bar::Foo { ensure out == 0; }";
        let document = parse_document("test.spec", source).expect("parse success");
        let Item::Contract(contract) = &document.items[0] else {
            panic!("expected contract");
        };
        assert_eq!(contract.target.name, "Bar::Foo");
    }

    #[test]
    fn allows_identifiers_with_keyword_prefixes() {
        let source = "contract for Foo { invariant for for_label(lb, i, ub, stride) {} }";
        let document = parse_document("test.spec", source).expect("parse success");
        let Item::Contract(contract) = &document.items[0] else {
            panic!("expected contract");
        };
        let Statement::Invariant(invariant) = &contract.body.statements[0] else {
            panic!("expected invariant");
        };
        assert_eq!(invariant.loop_name.name, "for_label");
    }

    #[test]
    fn rejects_empty_escaped_symbols() {
        let diagnostic = parse_document("test.spec", "contract for Foo { ensure `` == 0; }")
            .expect_err("parse failure");
        assert!(
            diagnostic
                .message
                .contains("escaped symbol cannot be empty")
        );
    }
}
