name: CI

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-repo
      - name: Build and test
        run: nix --print-build-logs build

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-repo
      - name: Set nix environment
        uses: nicknovitski/nix-develop@v1
        env:
          CI_BOT_PAT: "${{ secrets.CI_BUILD_TOKEN }}"
      - name: Run pre-commit checks
        run: pre-commit run --all-files --hook-stage manual
